{
  imports = [
    ./boot.nix
    ./console.nix
    ./filesystems.nix
    ./hardware.nix
    ./i18n.nix
    ./networking.nix
    ./nix.nix
    ./nixpkgs.nix
    ./secrets.nix
    ./security.nix
    ./services.nix
    ./swapDevices.nix
    ./system.nix
    ./time.nix
    ./users.nix
  ];
}
