{ pkgs, inputs, ... }: {
  environment = {
    sessionVariables = {
      EDITOR = "micro";
      NIXOS_OZONE_WL = "1";
      WLR_NO_HARDWARE_CURSORS = "1";
    };
    systemPackages = with pkgs; [
      _1password-cli
      _1password-gui
      adwaita-qt
      inputs.agenix.packages.${system}.default
      alacritty
      apostrophe
      bc
      bitwarden-desktop
      btop
      cf-terraforming
      codex
      coreutils
      curl
      #deskflow
      devbox
      devenv
      discord
      eyedropper
      fd
      fuzzel
      gedit
      ghostty
      gnome-builder
      gnome-extension-manager
      gnome-tweaks
      gnomeExtensions.appindicator
      gnomeExtensions.arcmenu
      gnomeExtensions.dash-to-panel
      gnomeExtensions.focus
      gnomeExtensions.paperwm
      gnomeExtensions.rounded-corners
      gnomeExtensions.tailscale-qs
      gnomeExtensions.user-themes-x
      google-chrome
      gparted
      home-manager
      hyfetch
      inkscape
      ironbar
      jdk
      jetbrains.idea-community
      kdePackages.kaccounts-integration
      kdePackages.kaccounts-providers
      kdePackages.karousel
      kdePackages.kdepim-addons
      kdePackages.kio-gdrive
      kdePackages.krohnkite
      kdePackages.signon-kwallet-extension
      kdePackages.signond
      lazygit
      libgnome-keyring
      logseq
      micro
      nix-index
      nixfmt-rfc-style
      nixos-icons
      nodejs_22
      nuclear
      nvd
      nwg-panel
      packwiz
      pam_u2f
      pavucontrol
      pika-backup
      prismlauncher
      ripgrep
      rofi-wayland
      scribus
      shellcheck
      sops
      swaylock
      swig
      terraform
      vim
      vlc
      vscode
      waybar
      windsurf
      yaru-theme
      yubikey-manager
      yubioath-flutter
      zettlr
    ];
  };
}
